/**
 * Common jargon that is NOT its own catalog page.
 * Used by termify.js to wrap first plain-text occurrences in .concept-body.
 * Do not list catalog concept names here — those should be .concept-link.
 */
window.__LEARN_GLOSSARY__ = {
  "amortized": "Averaged over a long sequence of operations, not one worst-case step.",
  "asymptotic": "About growth as input size tends to infinity, ignoring constants.",
  "invariant": "A property that stays true before/after each step of an algorithm or loop.",
  "abstraction": "Hiding detail behind a simpler interface or model.",
  "indirection": "Reaching data through an intermediate address or reference.",
  "contiguous": "Laid out in neighboring memory addresses with no gaps in the layout.",
  "opaque": "Hidden representation you use only through an interface.",
  "deterministic": "Same inputs always produce the same outputs/behavior.",
  "nondeterministic": "Behavior may vary (concurrency, randomness, or theoretical NFA branches).",
  "throughput": "Work completed per unit time.",
  "latency": "Time until one operation completes.",
  "bandwidth": "How much data a channel can carry per unit time.",
  "overhead": "Extra cost beyond the essential useful work.",
  "bottleneck": "The scarce resource that limits overall speed.",
  "race condition": "Outcome depends on unlucky timing between concurrent actors.",
  "critical section": "Code that must not run interleaved with conflicting concurrent code.",
  "mutex": "A mutual-exclusion lock: only one holder at a time.",
  "semaphore": "A counter for available permits; used to coordinate access.",
  "atomic": "Indivisible: appears to happen all at once to other threads.",
  "idempotent": "Doing it once or many times leaves the same final state.",
  "opaque pointer": "A pointer to an incomplete type you must not dereference directly.",
  "base case": "The non-recursive stopping condition in recursion/induction.",
  "inductive step": "Assuming the claim for smaller cases, prove it for the next.",
  "prerequisite": "Something that must be true/available before a step is valid.",
  "side effect": "A change to state beyond returning a value (I/O, mutation, etc.).",
  "pure function": "Output depends only on inputs; no observable side effects.",
  "immutable": "Cannot be changed after creation; updates make new values.",
  "mutable": "Can be changed in place after creation.",
  "serialization": "Turning structured data into a byte/text form for storage or the wire.",
  "deserialization": "Parsing bytes/text back into structured data.",
  "round-trip": "Encode then decode (or send then receive) back to an equivalent value.",
  "handshake": "Initial protocol messages that set up a connection or session.",
  "payload": "The useful data inside a packet/message, excluding headers.",
  "header": "Metadata fields that describe or route a payload.",
  "namespace": "A scope that keeps names from colliding.",
  "schema": "A description of allowed shape/types of data.",
  "migration": "A versioned change to a schema or stored data layout.",
  "hot path": "Code that runs very frequently; worth optimizing carefully.",
  "cold path": "Rarely run code (errors, init); optimize less aggressively.",
  "working set": "The memory pages/data actively used in a time window.",
  "locality": "Using nearby or recently used data — what makes caches work.",
  "thrashing": "Spending most time paging/caching instead of useful work.",
  "starvation": "A task never gets a needed resource because others keep winning.",
  "fairness": "Scheduling/allocation that avoids systematic starvation.",
  "quorum": "Minimum number of votes/replicas needed to decide.",
  "replica": "A copy of data kept for durability or scale.",
  "shard": "A horizontal partition of data across nodes.",
  "fan-out": "One request triggers many downstream requests.",
  "backpressure": "Slowing producers when consumers cannot keep up.",
  "tail latency": "High-percentile delays (p95/p99), not just the average.",
  "monotonic": "Always non-decreasing (or always non-increasing).",
  "commutative": "Order of combining does not change the result.",
  "associative": "Grouping of combining does not change the result.",
  "orthogonal": "Independent concerns that can change without interfering.",
  "canonical": "The preferred normal form of a value or representation.",
  "wire format": "How values are laid out in network bytes.",
  "ABI": "Application Binary Interface — low-level binary calling/layout contract.",
  "API": "Application Programming Interface — the callable surface of a component.",
  "SDK": "Software Development Kit — libraries/tools to build against an API.",
  "POSIX": "A family of OS interface standards common on Unix-like systems.",
  "endianness": "Byte order for multi-byte values (little vs big endian).",
  "alignment": "Addresses must be multiples of a size for a type/CPU.",
  "padding": "Unused bytes inserted to satisfy alignment or layout rules.",
  "word": "CPU's natural chunk size (often 32 or 64 bits).",
  "register": "Tiny ultra-fast storage inside the CPU.",
  "opcode": "The part of an instruction that says which operation to perform.",
  "operand": "A value or location an instruction operates on.",
  "segfault": "Crash from an invalid memory access (segmentation fault).",
  "null pointer": "A pointer that refers to no object (address 0 / None).",
  "dangling pointer": "A pointer to memory that was already freed/invalidated.",
  "buffer overflow": "Writing past the end of an allocated buffer.",
  "TOCTOU": "Time-of-check to time-of-use — a race on a checked then used resource.",
  "salt": "Extra random input mixed into hashing passwords to stop rainbow tables.",
  "nonce": "Number used once — prevents replay in crypto protocols.",
  "ciphertext": "Data after encryption.",
  "plaintext": "Data before encryption (or after decryption).",
  "digest": "Output of a hash function.",
  "certificate": "A signed document binding a public key to an identity.",
  "public key": "Sharable half of an asymmetric key pair.",
  "private key": "Secret half of an asymmetric key pair — never share it.",
  "symmetric key": "One shared secret used to encrypt and decrypt.",
  "adversary": "The modeled attacker in a security discussion.",
  "threat actor": "Who might attack you (script kiddie, insider, nation-state, …).",
  "attack surface": "The set of entry points an adversary can try.",
  "privilege escalation": "Gaining higher permissions than intended.",
  "sandbox": "Restricted environment that limits what code can do.",
  "capability": "An unforgeable token of authority to perform an action.",
  "ACL": "Access-control list — who may do what to a resource.",
  "RBAC": "Role-based access control — permissions via roles.",
  "least privilege": "Give only the permissions required — nothing more.",
  "defense in depth": "Multiple independent layers of protection.",
  "zero-cost abstraction": "High-level construct that compiles away with no runtime tax (ideal).",
  "technical debt": "Short-term shortcuts that make future changes more expensive.",
  "regression": "A previously working behavior that broke after a change.",
  "flake": "A test that fails intermittently without a real product bug (or hard-to-repro).",
  "fixture": "Setup data/state reused across tests.",
  "mock": "A stand-in object that records calls / returns canned answers in tests.",
  "stub": "A minimal stand-in that returns fixed responses.",
  "oracle": "A trusted source of correct answers to check against.",
  "heuristic": "A practical rule that is usually good, not guaranteed optimal.",
  "approximation algorithm": "Algorithm with a proven bound on how far from optimal it can be.",
  "reduction": "Transforming problem A into problem B to transfer hardness or algorithms.",
  "lower bound": "A proof that any algorithm needs at least this much work (in a model).",
  "upper bound": "A guarantee a specific algorithm never exceeds this cost.",
  "model of computation": "Assumptions about what operations cost (RAM model, comparisons, …).",
  "RAM model": "Simplified machine model where basic memory ops cost O(1).",
  "comparison model": "Cost counted by element comparisons only.",
  "stable sort": "Equal keys keep their original relative order.",
  "in-place": "Uses only a small extra memory beyond the input.",
  "destructive": "Overwrites / consumes the input as it runs.",
  "canonicalization": "Converting data to a single normal representation.",
  "escape hatch": "A deliberate way to bypass an abstraction when needed.",
  "footgun": "An API that makes dangerous misuse too easy.",
  "undefined behavior": "The language says nothing about what happens — anything may occur.",
  "implementation-defined": "Behavior must be consistent but is chosen by the compiler/runtime.",
  "unspecified behavior": "One of several valid behaviors; not a free-for-all like UB.",
  "short-circuit": "Boolean ops skipping the rest when the answer is already known.",
  "tail call": "A call in tail position that can reuse the current stack frame.",
  "continuation": "An explicit representation of 'what to do next'.",
  "closure": "A function bundled with the environment it captured.",
  "higher-order function": "A function that takes or returns functions.",
  "currying": "Turning a multi-arg function into a chain of single-arg functions.",
  "referential transparency": "An expression can be replaced by its value without changing meaning.",
  "totality": "A function finishes with a value on every input (no infinite loop/crash).",
  "partial function": "Not defined for every input.",
  "bijection": "One-to-one and onto correspondence between sets.",
  "injection": "One-to-one mapping — distinct inputs → distinct outputs.",
  "surjection": "Onto mapping — every output is hit by some input.",
  "cardinality": "Size of a set (how many elements).",
  "power set": "The set of all subsets of a set.",
  "equivalence relation": "Reflexive, symmetric, transitive relation — partitions a set.",
  "partial order": "Reflexive, antisymmetric, transitive — like ⊆ on sets.",
  "total order": "A partial order where every pair is comparable.",
  "DAG": "Directed acyclic graph — directed edges, no cycles.",
  "cycle": "A path that returns to its start.",
  "connected component": "A maximal set of vertices mutually reachable (undirected).",
  "strongly connected": "Every vertex reachable from every other (directed).",
  "cut": "A partition of vertices; cut edges cross the partition.",
  "spanning tree": "A tree that touches every vertex of a connected graph.",
  "planar graph": "Drawable in the plane with no edge crossings.",
  "degree": "Number of edges incident to a vertex (graphs) or polynomial degree (math).",
  "adjacency list": "Graph storage: per vertex, a list of neighbors.",
  "adjacency matrix": "Graph storage: a 2D array of edge presence/weights.",
  "incidence": "Relationship of an edge being attached to a vertex.",
  "frontier": "The set of discovered-but-not-finished nodes in a search.",
  "relaxation": "Updating a distance estimate when a cheaper path is found.",
  "augmenting path": "A path that can increase flow in a flow network.",
  "residual graph": "Graph of leftover capacities used by max-flow algorithms.",
  "cut capacity": "Total capacity of edges leaving an S-set in a flow network.",
  "potential function": "A numeric measure used in amortized analysis.",
  "token method": "Amortized analysis that pre-pays with tokens for future expensive ops.",
  "aggregate analysis": "Amortized method totaling cost of n ops then dividing.",
  "master theorem": "Cookbook bounds for many divide-and-conquer recurrences.",
  "recurrence": "An equation defining a sequence/cost in terms of smaller inputs.",
  "closed form": "A non-recursive formula for a sequence or cost.",
  "generating function": "A power series that encodes a sequence for algebraic attack.",
  "Bayes": "Updating beliefs about hypotheses given evidence.",
  "prior": "Belief before seeing the new evidence.",
  "posterior": "Belief after incorporating evidence.",
  "likelihood": "How probable the evidence is under a hypothesis.",
  "i.i.d.": "Independent and identically distributed random variables.",
  "variance": "Expected squared deviation from the mean.",
  "standard deviation": "Square root of variance — spread in original units.",
  "distribution": "The probabilities attached to possible outcomes of a random variable.",
  "PDF": "Probability density function for continuous variables.",
  "PMF": "Probability mass function for discrete variables.",
  "CDF": "Cumulative distribution — P(X ≤ x).",
  "heavy-tailed": "Outcomes far in the tail are more likely than a normal curve suggests.",
  "Markov": "Future depends on the present state, not the full past (Markov property).",
  "stationary": "Distribution does not change over time.",
  "ergodic": "Time averages match ensemble averages under conditions.",
  "feature": "An input variable to a learning model.",
  "label": "The target value a supervised model should predict.",
  "loss": "Numeric penalty for a bad prediction.",
  "objective": "The function being optimized (often a loss + regularizer).",
  "regularization": "Penalty on model complexity to reduce overfitting.",
  "hyperparameter": "A training setting chosen outside the learned parameters.",
  "epoch": "One full pass over the training set.",
  "batch": "A subset of examples used for one update step.",
  "learning rate": "Step size for gradient descent updates.",
  "gradient": "Vector of partial derivatives — steepest ascent direction of a function.",
  "local minimum": "A point lower than its neighborhood, maybe not the global lowest.",
  "convex": "Bowl-shaped: local minima are global (nice for optimization).",
  "generalization": "Performance on new data, not just the training set.",
  "train/test split": "Holding out data to estimate generalization.",
  "cross-validation": "Rotating holdout folds to get a stabler estimate.",
  "baseline": "A simple reference model/method you must beat.",
  "ablation": "Removing a component to measure how much it mattered.",
  "latency hiding": "Overlapping wait time with useful work.",
  "speculative execution": "CPU starts work before it knows it is needed.",
  "branch prediction": "Guessing which way an if will go to keep the pipeline full.",
  "hazard": "Pipeline conflict (data/control/structural) that risks wrong results.",
  "forwarding": "Bypassing results to a later stage to reduce pipeline stalls.",
  "stall": "Pipeline bubble — a stage waits.",
  "cache line": "The fixed-size block moved between cache levels.",
  "TLB": "Translation Lookaside Buffer — cache of virtual→physical mappings.",
  "page fault": "Needed page is not in RAM; OS must load or map it.",
  "swap": "Moving pages between RAM and disk.",
  "DMA": "Direct Memory Access — device copies memory without CPU per byte.",
  "context switch": "Saving one thread/process state and loading another.",
  "user space": "Where normal apps run with restricted privileges.",
  "kernel space": "Privileged OS code and data.",
  "ring 0": "Most privileged CPU privilege level (kernel, typically).",
  "syscall number": "Integer identifying which system call to invoke.",
  "errno": "Thread-local error code set by failed C library/OS calls.",
  "blocking I/O": "Call waits until the operation completes.",
  "non-blocking I/O": "Call returns immediately if it would have to wait.",
  "async I/O": "Completion happens later; you are notified via callback/event/future.",
  "event loop": "Single-threaded loop that dispatches I/O and timer callbacks.",
  "green thread": "User-scheduled lightweight thread not 1:1 with OS threads.",
  "preemption": "Scheduler forcibly switches tasks without them yielding.",
  "cooperative scheduling": "Tasks yield deliberately; no forced preemption.",
  "priority inversion": "High-priority task waits behind a low-priority one holding a lock.",
  "writer preference": "A lock policy that favors writers over readers (or vice versa).",
  "serializability": "Txn result equals some serial order of those transactions.",
  "linearizability": "Each op appears instantaneously in real-time order (strong shared-object consistency).",
  "eventual consistency": "Replicas converge if updates stop — intermediate reads may be stale.",
  "causal consistency": "Respects happens-before; concurrent writes may be seen in different orders.",
  "split brain": "Two sides of a partition both think they are primary.",
  "poison message": "A message that repeatedly crashes consumers.",
  "dead letter queue": "Where poison/undeliverable messages are set aside.",
  "at-most-once": "May lose messages; never duplicates.",
  "at-least-once": "May duplicate; will not silently drop after ack semantics.",
  "two-phase commit": "Distributed commit protocol with prepare + commit phases.",
  "vector clock": "Per-process counters that track causal history richer than Lamport clocks.",
  "CRDT": "Conflict-free replicated data type — merges concurrent updates cleanly.",
  "CAP": "Consistency / Availability / Partition tolerance tradeoff slogan for distributed DBs.",
  "BASE": "Basically Available, Soft state, Eventual consistency — loose contrast to ACID.",
  "OLTP": "Online transaction processing — many small writes/reads.",
  "OLAP": "Online analytical processing — large analytical scans/aggregations.",
  "materialized view": "Precomputed query result stored for fast read.",
  "covering index": "Index that includes all columns a query needs — avoids table lookup.",
  "cardinality (DB)": "How many distinct values a column has — affects optimizer choices.",
  "selectivity": "How strongly a predicate filters rows.",
  "vacuum": "Maintenance that reclaims dead tuple space (esp. PostgreSQL).",
  "MVCC": "Multi-version concurrency control — readers see snapshots without blocking writers as much.",
  "WAL": "Write-ahead log — durable log of changes before data pages.",
  "checkpoint": "Flushing dirty state so older log can be truncated.",
  "point-in-time recovery": "Restore DB state to a chosen moment using backups + logs.",
  "connection pool": "Reusable DB connections to avoid connect overhead.",
  "N+1 query": "Fetching a list then querying once per item — accidental query storm.",
  "ORM": "Object-relational mapper — objects mapped to tables.",
  "prepared statement": "Parsed SQL with bind parameters — safer and often faster to reuse.",
  "SQL injection": "Attacker-controlled SQL fragments executed by your DB.",
  "XSS": "Cross-site scripting — injecting script into someone else's browser session.",
  "CSRF": "Cross-site request forgery — tricking a browser into authenticated requests.",
  "CORS": "Cross-Origin Resource Sharing — browser rules for cross-site HTTP.",
  "same-origin policy": "Browser rule isolating pages by scheme/host/port.",
  "CSP": "Content Security Policy — headers limiting script/resource sources.",
  "HSTS": "HTTP Strict Transport Security — force HTTPS for a host.",
  "MITM": "Man-in-the-middle — attacker between two parties on the channel.",
  "phishing": "Social engineering to steal credentials or consent.",
  "exfiltration": "Unauthorized data leaving your system.",
  "lateral movement": "Attacker hopping deeper inside a network after entry.",
  "zero-day": "Exploit for a vulnerability with no patch available yet.",
  "CVSS": "Common scoring system for vulnerability severity.",
  "SBOM": "Software bill of materials — inventory of components/dependencies.",
  "Master theorem": "Cookbook asymptotic solutions for T(n)=aT(n/b)+f(n) recurrences.",
  "diagonalization": "Construct an object that differs from each listed candidate on the diagonal entry.",
  "contrapositive": "¬Q ⇒ ¬P — logically equivalent to P ⇒ Q.",
  "proof by contradiction": "Assume the claim is false and derive an impossibility.",
  "posterior": "Probability of a hypothesis after seeing evidence (Bayes).",
  "prior": "Belief about a hypothesis before seeing the current evidence.",
  "likelihood": "P(evidence | hypothesis) — how well a hypothesis predicts the data.",
  "base rate": "Prior frequency of a class/event in the population.",
  "Chebyshev's inequality": "P(|X−μ|≥t) ≤ Var(X)/t² — variance-only tail bound.",
  "concentration": "Random quantities stay close to their mean with high probability.",
  "Las Vegas algorithm": "Always correct; only the runtime is random.",
  "Monte Carlo algorithm": "May err with small probability; often faster/simpler.",
  "stationary distribution": "Probability vector π with π = πP for a Markov chain.",
  "memoryless": "Future depends on the present state, not the full history.",
  "singular value": "Stretch factor along a principal axis in an SVD.",
  "PCA": "Principal component analysis — keep top-variance directions (SVD of centered data).",
  "cross-entropy": "Loss comparing a predicted distribution to a target distribution.",
  "regularization": "Penalty or constraint that discourages overfitting.",
  "hypothesis class": "Family of models you allow the learner to pick from.",
  "self-information": "−log p(event) — surprise of a single outcome.",
  "Shannon entropy": "Average self-information of a discrete distribution."
};
